import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabaseServer'

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url)
  const token_hash = searchParams.get('token_hash')
  const type = searchParams.get('type')

  if (!token_hash || type !== 'recovery') {
    return NextResponse.redirect(`${origin}/login?error=Missing_token`)
  }

  const supabase = await createClient()

  // 1. Verify the token securely. 
  // (This automatically sets the session cookie via your supabaseServer.ts logic)
  const { data, error } = await supabase.auth.verifyOtp({
    type: 'recovery',
    token_hash,
  })
  
  if (error) {
    console.error("Supabase OTP Error:", error.message)
    return NextResponse.redirect(`${origin}/login?error=${encodeURIComponent(error.message)}`)
  }


  if (data?.user) {
    // 2. Force the password change trap back on
    await supabase
      .from('investors')
      .update({ requires_password_change: true })
      .eq('user_id', data.user.id)

    // 3. Redirect to settings. 
    // Next.js will automatically attach the Set-Cookie headers generated by verifyOtp!
    return NextResponse.redirect(`${origin}/dashboard/settings`)
  }

  // Fallback
  return NextResponse.redirect(`${origin}/login?error=Unknown_error`)
}